/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.db.models;


import com.diluv.hilo.db.models.tables.Project;
import com.diluv.hilo.db.models.tables.ProjectFile;
import com.diluv.hilo.db.models.tables.ProjectFileProcessing;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Diluv extends SchemaImpl {

    private static final long serialVersionUID = -169260587;

    /**
     * The reference instance of <code>diluv</code>
     */
    public static final Diluv DILUV = new Diluv();

    /**
     * The table <code>diluv.PROJECT</code>.
     */
    public final Project PROJECT = com.diluv.hilo.db.models.tables.Project.PROJECT;

    /**
     * The table <code>diluv.PROJECT_FILE</code>.
     */
    public final ProjectFile PROJECT_FILE = com.diluv.hilo.db.models.tables.ProjectFile.PROJECT_FILE;

    /**
     * The table <code>diluv.PROJECT_FILE_PROCESSING</code>.
     */
    public final ProjectFileProcessing PROJECT_FILE_PROCESSING = com.diluv.hilo.db.models.tables.ProjectFileProcessing.PROJECT_FILE_PROCESSING;

    /**
     * No further instances allowed
     */
    private Diluv() {
        super("diluv", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Project.PROJECT,
                ProjectFile.PROJECT_FILE,
                ProjectFileProcessing.PROJECT_FILE_PROCESSING);
    }
}
