/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.db.models;


import com.diluv.hilo.db.models.tables.Project;
import com.diluv.hilo.db.models.tables.ProjectFile;
import com.diluv.hilo.db.models.tables.ProjectFileProcessing;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in diluv
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>diluv.PROJECT</code>.
     */
    public static final Project PROJECT = com.diluv.hilo.db.models.tables.Project.PROJECT;

    /**
     * The table <code>diluv.PROJECT_FILE</code>.
     */
    public static final ProjectFile PROJECT_FILE = com.diluv.hilo.db.models.tables.ProjectFile.PROJECT_FILE;

    /**
     * The table <code>diluv.PROJECT_FILE_PROCESSING</code>.
     */
    public static final ProjectFileProcessing PROJECT_FILE_PROCESSING = com.diluv.hilo.db.models.tables.ProjectFileProcessing.PROJECT_FILE_PROCESSING;
}
