/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.models.tables.records;


import com.diluv.hilo.models.tables.ProjectFileProcessing;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileProcessingRecord extends UpdatableRecordImpl<ProjectFileProcessingRecord> implements Record5<Long, String, Boolean, String, Timestamp> {

    private static final long serialVersionUID = 2091581549;

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.SUCCESSFUL</code>.
     */
    public void setSuccessful(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.SUCCESSFUL</code>.
     */
    public Boolean getSuccessful() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.LOGS</code>.
     */
    public void setLogs(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.LOGS</code>.
     */
    public String getLogs() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.SUCCESSFUL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getSuccessful();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLogs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value1(Long value) {
        setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value3(Boolean value) {
        setSuccessful(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value4(String value) {
        setLogs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord values(Long value1, String value2, Boolean value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord() {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);
    }

    /**
     * Create a detached, initialised ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord(Long projectFileId, String status, Boolean successful, String logs, Timestamp createdAt) {
        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);

        set(0, projectFileId);
        set(1, status);
        set(2, successful);
        set(3, logs);
        set(4, createdAt);
    }
}
