/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.models.tables.records;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import com.diluv.hilo.models.tables.ProjectFileProcessing;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectFileProcessingRecord extends UpdatableRecordImpl<ProjectFileProcessingRecord> implements Record5<Long, String, Boolean, String, Timestamp> {

    private static final long serialVersionUID = 2091581549;

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public void setProjectFileId (Long value) {

        this.set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID</code>.
     */
    public Long getProjectFileId () {

        return (Long) this.get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public void setStatus (String value) {

        this.set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.STATUS</code>.
     */
    public String getStatus () {

        return (String) this.get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.SUCCESSFUL</code>.
     */
    public void setSuccessful (Boolean value) {

        this.set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.SUCCESSFUL</code>.
     */
    public Boolean getSuccessful () {

        return (Boolean) this.get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.LOGS</code>.
     */
    public void setLogs (String value) {

        this.set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.LOGS</code>.
     */
    public String getLogs () {

        return (String) this.get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public void setCreatedAt (Timestamp value) {

        this.set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE_PROCESSING.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt () {

        return (Timestamp) this.get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key () {

        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, String, Timestamp> fieldsRow () {

        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Boolean, String, Timestamp> valuesRow () {

        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1 () {

        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2 () {

        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3 () {

        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.SUCCESSFUL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4 () {

        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5 () {

        return ProjectFileProcessing.PROJECT_FILE_PROCESSING.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1 () {

        return this.getProjectFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2 () {

        return this.getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3 () {

        return this.getSuccessful();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4 () {

        return this.getLogs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5 () {

        return this.getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value1 (Long value) {

        this.setProjectFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value2 (String value) {

        this.setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value3 (Boolean value) {

        this.setSuccessful(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value4 (String value) {

        this.setLogs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord value5 (Timestamp value) {

        this.setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileProcessingRecord values (Long value1, String value2, Boolean value3, String value4, Timestamp value5) {

        this.value1(value1);
        this.value2(value2);
        this.value3(value3);
        this.value4(value4);
        this.value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord () {

        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);
    }

    /**
     * Create a detached, initialised ProjectFileProcessingRecord
     */
    public ProjectFileProcessingRecord (Long projectFileId, String status, Boolean successful, String logs, Timestamp createdAt) {

        super(ProjectFileProcessing.PROJECT_FILE_PROCESSING);

        this.set(0, projectFileId);
        this.set(1, status);
        this.set(2, successful);
        this.set(3, logs);
        this.set(4, createdAt);
    }
}
