/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.models.tables.records;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import com.diluv.hilo.models.tables.Project;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record14<Long, String, String, String, String, String, String, Long, Boolean, Boolean, Timestamp, Timestamp, Long, Long> {

    private static final long serialVersionUID = 530023422;

    /**
     * Setter for <code>diluv.PROJECT.ID</code>.
     */
    public void setId (Long value) {

        this.set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.ID</code>.
     */
    public Long getId () {

        return (Long) this.get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT.NAME</code>.
     */
    public void setName (String value) {

        this.set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.NAME</code>.
     */
    public String getName () {

        return (String) this.get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT.SHORT_DESCRIPTION</code>.
     */
    public void setShortDescription (String value) {

        this.set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.SHORT_DESCRIPTION</code>.
     */
    public String getShortDescription () {

        return (String) this.get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT.DESCRIPTION</code>.
     */
    public void setDescription (String value) {

        this.set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.DESCRIPTION</code>.
     */
    public String getDescription () {

        return (String) this.get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT.DESCRIPTION_TYPE</code>.
     */
    public void setDescriptionType (String value) {

        this.set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.DESCRIPTION_TYPE</code>.
     */
    public String getDescriptionType () {

        return (String) this.get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT.SLUG</code>.
     */
    public void setSlug (String value) {

        this.set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.SLUG</code>.
     */
    public String getSlug () {

        return (String) this.get(5);
    }

    /**
     * Setter for <code>diluv.PROJECT.LOGO</code>.
     */
    public void setLogo (String value) {

        this.set(6, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.LOGO</code>.
     */
    public String getLogo () {

        return (String) this.get(6);
    }

    /**
     * Setter for <code>diluv.PROJECT.TOTAL_DOWNLOADS</code>.
     */
    public void setTotalDownloads (Long value) {

        this.set(7, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.TOTAL_DOWNLOADS</code>.
     */
    public Long getTotalDownloads () {

        return (Long) this.get(7);
    }

    /**
     * Setter for <code>diluv.PROJECT.NEW_PROJECT</code>.
     */
    public void setNewProject (Boolean value) {

        this.set(8, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.NEW_PROJECT</code>.
     */
    public Boolean getNewProject () {

        return (Boolean) this.get(8);
    }

    /**
     * Setter for <code>diluv.PROJECT.DELETED</code>.
     */
    public void setDeleted (Boolean value) {

        this.set(9, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.DELETED</code>.
     */
    public Boolean getDeleted () {

        return (Boolean) this.get(9);
    }

    /**
     * Setter for <code>diluv.PROJECT.UPDATED_AT</code>.
     */
    public void setUpdatedAt (Timestamp value) {

        this.set(10, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt () {

        return (Timestamp) this.get(10);
    }

    /**
     * Setter for <code>diluv.PROJECT.CREATED_AT</code>.
     */
    public void setCreatedAt (Timestamp value) {

        this.set(11, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt () {

        return (Timestamp) this.get(11);
    }

    /**
     * Setter for <code>diluv.PROJECT.PROJECT_TYPE_ID</code>.
     */
    public void setProjectTypeId (Long value) {

        this.set(12, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.PROJECT_TYPE_ID</code>.
     */
    public Long getProjectTypeId () {

        return (Long) this.get(12);
    }

    /**
     * Setter for <code>diluv.PROJECT.USER_ID</code>.
     */
    public void setUserId (Long value) {

        this.set(13, value);
    }

    /**
     * Getter for <code>diluv.PROJECT.USER_ID</code>.
     */
    public Long getUserId () {

        return (Long) this.get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key () {

        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, String, String, Long, Boolean, Boolean, Timestamp, Timestamp, Long, Long> fieldsRow () {

        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, String, String, Long, Boolean, Boolean, Timestamp, Timestamp, Long, Long> valuesRow () {

        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1 () {

        return Project.PROJECT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2 () {

        return Project.PROJECT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3 () {

        return Project.PROJECT.SHORT_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4 () {

        return Project.PROJECT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5 () {

        return Project.PROJECT.DESCRIPTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6 () {

        return Project.PROJECT.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7 () {

        return Project.PROJECT.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8 () {

        return Project.PROJECT.TOTAL_DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9 () {

        return Project.PROJECT.NEW_PROJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10 () {

        return Project.PROJECT.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11 () {

        return Project.PROJECT.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12 () {

        return Project.PROJECT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13 () {

        return Project.PROJECT.PROJECT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14 () {

        return Project.PROJECT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1 () {

        return this.getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2 () {

        return this.getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3 () {

        return this.getShortDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4 () {

        return this.getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5 () {

        return this.getDescriptionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6 () {

        return this.getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7 () {

        return this.getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8 () {

        return this.getTotalDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9 () {

        return this.getNewProject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10 () {

        return this.getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11 () {

        return this.getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12 () {

        return this.getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13 () {

        return this.getProjectTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14 () {

        return this.getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value1 (Long value) {

        this.setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value2 (String value) {

        this.setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value3 (String value) {

        this.setShortDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value4 (String value) {

        this.setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value5 (String value) {

        this.setDescriptionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value6 (String value) {

        this.setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value7 (String value) {

        this.setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value8 (Long value) {

        this.setTotalDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value9 (Boolean value) {

        this.setNewProject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value10 (Boolean value) {

        this.setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value11 (Timestamp value) {

        this.setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value12 (Timestamp value) {

        this.setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value13 (Long value) {

        this.setProjectTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord value14 (Long value) {

        this.setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRecord values (Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, Boolean value9, Boolean value10, Timestamp value11, Timestamp value12, Long value13, Long value14) {

        this.value1(value1);
        this.value2(value2);
        this.value3(value3);
        this.value4(value4);
        this.value5(value5);
        this.value6(value6);
        this.value7(value7);
        this.value8(value8);
        this.value9(value9);
        this.value10(value10);
        this.value11(value11);
        this.value12(value12);
        this.value13(value13);
        this.value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord () {

        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord (Long id, String name, String shortDescription, String description, String descriptionType, String slug, String logo, Long totalDownloads, Boolean newProject, Boolean deleted, Timestamp updatedAt, Timestamp createdAt, Long projectTypeId, Long userId) {

        super(Project.PROJECT);

        this.set(0, id);
        this.set(1, name);
        this.set(2, shortDescription);
        this.set(3, description);
        this.set(4, descriptionType);
        this.set(5, slug);
        this.set(6, logo);
        this.set(7, totalDownloads);
        this.set(8, newProject);
        this.set(9, deleted);
        this.set(10, updatedAt);
        this.set(11, createdAt);
        this.set(12, projectTypeId);
        this.set(13, userId);
    }
}
