/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.models.tables.records;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import com.diluv.hilo.models.tables.ProjectFile;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.9.3" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectFileRecord extends UpdatableRecordImpl<ProjectFileRecord> implements Record14<Long, String, String, String, Long, Long, String, Timestamp, Boolean, Boolean, Boolean, Long, Long, Long> {

    private static final long serialVersionUID = 1221227218;

    /**
     * Setter for <code>diluv.PROJECT_FILE.ID</code>.
     */
    public void setId (Long value) {

        this.set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.ID</code>.
     */
    public Long getId () {

        return (Long) this.get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.SHA512</code>.
     */
    public void setSha512 (String value) {

        this.set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.SHA512</code>.
     */
    public String getSha512 () {

        return (String) this.get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.FILE_NAME</code>.
     */
    public void setFileName (String value) {

        this.set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.FILE_NAME</code>.
     */
    public String getFileName () {

        return (String) this.get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.DISPLAY_NAME</code>.
     */
    public void setDisplayName (String value) {

        this.set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.DISPLAY_NAME</code>.
     */
    public String getDisplayName () {

        return (String) this.get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.SIZE</code>.
     */
    public void setSize (Long value) {

        this.set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.SIZE</code>.
     */
    public Long getSize () {

        return (Long) this.get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.DOWNLOADS</code>.
     */
    public void setDownloads (Long value) {

        this.set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.DOWNLOADS</code>.
     */
    public Long getDownloads () {

        return (Long) this.get(5);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.RELEASE_TYPE</code>.
     */
    public void setReleaseType (String value) {

        this.set(6, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.RELEASE_TYPE</code>.
     */
    public String getReleaseType () {

        return (String) this.get(6);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.CREATED_AT</code>.
     */
    public void setCreatedAt (Timestamp value) {

        this.set(7, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt () {

        return (Timestamp) this.get(7);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PUBLIC</code>.
     */
    public void setPublic (Boolean value) {

        this.set(8, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PUBLIC</code>.
     */
    public Boolean getPublic () {

        return (Boolean) this.get(8);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PROCESSING</code>.
     */
    public void setProcessing (Boolean value) {

        this.set(9, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PROCESSING</code>.
     */
    public Boolean getProcessing () {

        return (Boolean) this.get(9);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.REVIEW_NEEDED</code>.
     */
    public void setReviewNeeded (Boolean value) {

        this.set(10, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.REVIEW_NEEDED</code>.
     */
    public Boolean getReviewNeeded () {

        return (Boolean) this.get(10);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PARENT_ID</code>.
     */
    public void setParentId (Long value) {

        this.set(11, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PARENT_ID</code>.
     */
    public Long getParentId () {

        return (Long) this.get(11);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PROJECT_ID</code>.
     */
    public void setProjectId (Long value) {

        this.set(12, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PROJECT_ID</code>.
     */
    public Long getProjectId () {

        return (Long) this.get(12);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.USER_ID</code>.
     */
    public void setUserId (Long value) {

        this.set(13, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.USER_ID</code>.
     */
    public Long getUserId () {

        return (Long) this.get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key () {

        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, Long, Long, String, Timestamp, Boolean, Boolean, Boolean, Long, Long, Long> fieldsRow () {

        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, Long, Long, String, Timestamp, Boolean, Boolean, Boolean, Long, Long, Long> valuesRow () {

        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1 () {

        return ProjectFile.PROJECT_FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2 () {

        return ProjectFile.PROJECT_FILE.SHA512;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3 () {

        return ProjectFile.PROJECT_FILE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4 () {

        return ProjectFile.PROJECT_FILE.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5 () {

        return ProjectFile.PROJECT_FILE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6 () {

        return ProjectFile.PROJECT_FILE.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7 () {

        return ProjectFile.PROJECT_FILE.RELEASE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8 () {

        return ProjectFile.PROJECT_FILE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9 () {

        return ProjectFile.PROJECT_FILE.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10 () {

        return ProjectFile.PROJECT_FILE.PROCESSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11 () {

        return ProjectFile.PROJECT_FILE.REVIEW_NEEDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12 () {

        return ProjectFile.PROJECT_FILE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13 () {

        return ProjectFile.PROJECT_FILE.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14 () {

        return ProjectFile.PROJECT_FILE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1 () {

        return this.getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2 () {

        return this.getSha512();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3 () {

        return this.getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4 () {

        return this.getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5 () {

        return this.getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6 () {

        return this.getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7 () {

        return this.getReleaseType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8 () {

        return this.getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9 () {

        return this.getPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10 () {

        return this.getProcessing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11 () {

        return this.getReviewNeeded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12 () {

        return this.getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13 () {

        return this.getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14 () {

        return this.getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value1 (Long value) {

        this.setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value2 (String value) {

        this.setSha512(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value3 (String value) {

        this.setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value4 (String value) {

        this.setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value5 (Long value) {

        this.setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value6 (Long value) {

        this.setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value7 (String value) {

        this.setReleaseType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value8 (Timestamp value) {

        this.setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value9 (Boolean value) {

        this.setPublic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value10 (Boolean value) {

        this.setProcessing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value11 (Boolean value) {

        this.setReviewNeeded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value12 (Long value) {

        this.setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value13 (Long value) {

        this.setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value14 (Long value) {

        this.setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord values (Long value1, String value2, String value3, String value4, Long value5, Long value6, String value7, Timestamp value8, Boolean value9, Boolean value10, Boolean value11, Long value12, Long value13, Long value14) {

        this.value1(value1);
        this.value2(value2);
        this.value3(value3);
        this.value4(value4);
        this.value5(value5);
        this.value6(value6);
        this.value7(value7);
        this.value8(value8);
        this.value9(value9);
        this.value10(value10);
        this.value11(value11);
        this.value12(value12);
        this.value13(value13);
        this.value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileRecord
     */
    public ProjectFileRecord () {

        super(ProjectFile.PROJECT_FILE);
    }

    /**
     * Create a detached, initialised ProjectFileRecord
     */
    public ProjectFileRecord (Long id, String sha512, String fileName, String displayName, Long size, Long downloads, String releaseType, Timestamp createdAt, Boolean public_, Boolean processing, Boolean reviewNeeded, Long parentId, Long projectId, Long userId) {

        super(ProjectFile.PROJECT_FILE);

        this.set(0, id);
        this.set(1, sha512);
        this.set(2, fileName);
        this.set(3, displayName);
        this.set(4, size);
        this.set(5, downloads);
        this.set(6, releaseType);
        this.set(7, createdAt);
        this.set(8, public_);
        this.set(9, processing);
        this.set(10, reviewNeeded);
        this.set(11, parentId);
        this.set(12, projectId);
        this.set(13, userId);
    }
}
