/*
 * This file is generated by jOOQ.
*/
package com.diluv.hilo.models;


import com.diluv.hilo.models.tables.ProjectFile;
import com.diluv.hilo.models.tables.ProjectFileProcessing;
import com.diluv.hilo.models.tables.records.ProjectFileProcessingRecord;
import com.diluv.hilo.models.tables.records.ProjectFileRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>diluv</code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ProjectFileRecord, Long> IDENTITY_PROJECT_FILE = Identities0.IDENTITY_PROJECT_FILE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProjectFileRecord> KEY_PROJECT_FILE_PRIMARY = UniqueKeys0.KEY_PROJECT_FILE_PRIMARY;
    public static final UniqueKey<ProjectFileProcessingRecord> KEY_PROJECT_FILE_PROCESSING_PRIMARY = UniqueKeys0.KEY_PROJECT_FILE_PROCESSING_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProjectFileRecord, ProjectFileRecord> PROJECT_FILE_IBFK_1 = ForeignKeys0.PROJECT_FILE_IBFK_1;
    public static final ForeignKey<ProjectFileProcessingRecord, ProjectFileRecord> PROJECT_FILE_PROCESSING_IBFK_1 = ForeignKeys0.PROJECT_FILE_PROCESSING_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ProjectFileRecord, Long> IDENTITY_PROJECT_FILE = createIdentity(ProjectFile.PROJECT_FILE, ProjectFile.PROJECT_FILE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ProjectFileRecord> KEY_PROJECT_FILE_PRIMARY = createUniqueKey(ProjectFile.PROJECT_FILE, "KEY_PROJECT_FILE_PRIMARY", ProjectFile.PROJECT_FILE.ID);
        public static final UniqueKey<ProjectFileProcessingRecord> KEY_PROJECT_FILE_PROCESSING_PRIMARY = createUniqueKey(ProjectFileProcessing.PROJECT_FILE_PROCESSING, "KEY_PROJECT_FILE_PROCESSING_PRIMARY", ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID, ProjectFileProcessing.PROJECT_FILE_PROCESSING.STATUS);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ProjectFileRecord, ProjectFileRecord> PROJECT_FILE_IBFK_1 = createForeignKey(com.diluv.hilo.models.Keys.KEY_PROJECT_FILE_PRIMARY, ProjectFile.PROJECT_FILE, "PROJECT_FILE_ibfk_1", ProjectFile.PROJECT_FILE.PARENT_ID);
        public static final ForeignKey<ProjectFileProcessingRecord, ProjectFileRecord> PROJECT_FILE_PROCESSING_IBFK_1 = createForeignKey(com.diluv.hilo.models.Keys.KEY_PROJECT_FILE_PRIMARY, ProjectFileProcessing.PROJECT_FILE_PROCESSING, "PROJECT_FILE_PROCESSING_ibfk_1", ProjectFileProcessing.PROJECT_FILE_PROCESSING.PROJECT_FILE_ID);
    }
}
