/*
 * This file is generated by jOOQ.
 */
package com.diluv.hilo.db.models.tables.records;


import com.diluv.hilo.db.models.tables.ProjectFile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ProjectFileRecord extends UpdatableRecordImpl<ProjectFileRecord> implements Record17<Long, String, String, String, Long, String, Long, String, Timestamp, Boolean, Boolean, Boolean, Boolean, Boolean, Long, Long, Long> {

    private static final long serialVersionUID = 1274521285;

    /**
     * Setter for <code>diluv.PROJECT_FILE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.SHA512</code>.
     */
    public void setSha512(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.SHA512</code>.
     */
    public String getSha512() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.FILE_NAME</code>.
     */
    public void setFileName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.FILE_NAME</code>.
     */
    public String getFileName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.DISPLAY_NAME</code>.
     */
    public void setDisplayName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.DISPLAY_NAME</code>.
     */
    public String getDisplayName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.SIZE</code>.
     */
    public void setSize(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.SIZE</code>.
     */
    public Long getSize() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.CHANGELOG</code>.
     */
    public void setChangelog(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.CHANGELOG</code>.
     */
    public String getChangelog() {
        return (String) get(5);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.DOWNLOADS</code>.
     */
    public void setDownloads(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.DOWNLOADS</code>.
     */
    public Long getDownloads() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.RELEASE_TYPE</code>.
     */
    public void setReleaseType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.RELEASE_TYPE</code>.
     */
    public String getReleaseType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PUBLIC</code>.
     */
    public void setPublic(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PUBLIC</code>.
     */
    public Boolean getPublic() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PROCESSING</code>.
     */
    public void setProcessing(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PROCESSING</code>.
     */
    public Boolean getProcessing() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.REVIEW_NEEDED</code>.
     */
    public void setReviewNeeded(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.REVIEW_NEEDED</code>.
     */
    public Boolean getReviewNeeded() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.ARCHIVE</code>.
     */
    public void setArchive(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.ARCHIVE</code>.
     */
    public Boolean getArchive() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.DELETED</code>.
     */
    public void setDeleted(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.DELETED</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PARENT_ID</code>.
     */
    public void setParentId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PARENT_ID</code>.
     */
    public Long getParentId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.PROJECT_ID</code>.
     */
    public void setProjectId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.PROJECT_ID</code>.
     */
    public Long getProjectId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>diluv.PROJECT_FILE.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>diluv.PROJECT_FILE.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, String, String, Long, String, Long, String, Timestamp, Boolean, Boolean, Boolean, Boolean, Boolean, Long, Long, Long> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, String, String, Long, String, Long, String, Timestamp, Boolean, Boolean, Boolean, Boolean, Boolean, Long, Long, Long> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProjectFile.PROJECT_FILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProjectFile.PROJECT_FILE.SHA512;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProjectFile.PROJECT_FILE.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProjectFile.PROJECT_FILE.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return ProjectFile.PROJECT_FILE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProjectFile.PROJECT_FILE.CHANGELOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ProjectFile.PROJECT_FILE.DOWNLOADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return ProjectFile.PROJECT_FILE.RELEASE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ProjectFile.PROJECT_FILE.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return ProjectFile.PROJECT_FILE.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return ProjectFile.PROJECT_FILE.PROCESSING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return ProjectFile.PROJECT_FILE.REVIEW_NEEDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field13() {
        return ProjectFile.PROJECT_FILE.ARCHIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return ProjectFile.PROJECT_FILE.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return ProjectFile.PROJECT_FILE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return ProjectFile.PROJECT_FILE.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return ProjectFile.PROJECT_FILE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSha512();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getChangelog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getReleaseType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getProcessing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getReviewNeeded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component13() {
        return getArchive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component15() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSha512();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getChangelog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getReleaseType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getPublic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getProcessing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getReviewNeeded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value13() {
        return getArchive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value2(String value) {
        setSha512(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value3(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value4(String value) {
        setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value5(Long value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value6(String value) {
        setChangelog(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value7(Long value) {
        setDownloads(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value8(String value) {
        setReleaseType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value10(Boolean value) {
        setPublic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value11(Boolean value) {
        setProcessing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value12(Boolean value) {
        setReviewNeeded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value13(Boolean value) {
        setArchive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value14(Boolean value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value15(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value16(Long value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord value17(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectFileRecord values(Long value1, String value2, String value3, String value4, Long value5, String value6, Long value7, String value8, Timestamp value9, Boolean value10, Boolean value11, Boolean value12, Boolean value13, Boolean value14, Long value15, Long value16, Long value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectFileRecord
     */
    public ProjectFileRecord() {
        super(ProjectFile.PROJECT_FILE);
    }

    /**
     * Create a detached, initialised ProjectFileRecord
     */
    public ProjectFileRecord(Long id, String sha512, String fileName, String displayName, Long size, String changelog, Long downloads, String releaseType, Timestamp createdAt, Boolean public_, Boolean processing, Boolean reviewNeeded, Boolean archive, Boolean deleted, Long parentId, Long projectId, Long userId) {
        super(ProjectFile.PROJECT_FILE);

        set(0, id);
        set(1, sha512);
        set(2, fileName);
        set(3, displayName);
        set(4, size);
        set(5, changelog);
        set(6, downloads);
        set(7, releaseType);
        set(8, createdAt);
        set(9, public_);
        set(10, processing);
        set(11, reviewNeeded);
        set(12, archive);
        set(13, deleted);
        set(14, parentId);
        set(15, projectId);
        set(16, userId);
    }
}
